HF-76 : 시큐리티 구현
Likelion-YeungNam-Univ/12th-Gible-BE pull request #11
Opened 2024-07-16 15:55 UTC by Tentennball

## 개요
- JWT사용을 위한 시큐리티 구현

## 구현 사항
- jwtTokenProvider 구현
- jwtAuthenticationFilter 구현
- SecurityConfig 구현
- UserDetails, UserDetailsService 구현
- 소셜로그인을 위해 signinReq 수정
## 기타
 - OAuth2 시큐리티 사용하면 가능할것 같긴함(좀 걸릴듯..?) 근데 안써도 구현은 가능함
 - 이후 소셜로그인은 프론트에서 인가 코드 넘겨주면 그거로 구현가능함

2024-07-16 15:56 UTC, Tentennball commented on src/main/java/gible/config/SecurityConfig.java
> +                                        "/auth/token"//라우팅 아직 설정x
해당 부분은 후에 라우팅 어느정도 정해지면 상수로 관리예정입니다.

2024-07-16 16:19 UTC, DaeYoung0726 commented
고생하셨습니다!
소통할때 오류가 있었는지 틀어진 부분이 하나 있는데 그거에 대해서 코멘트 남겨놓겠습니다!

2024-07-16 16:26 UTC, DaeYoung0726 commented on src/main/java/gible/domain/security/common/SecurityUserDetails.java
>      }
이 부분에서 user의 이름인 name을 반환하셨는데
카톡으로 얘기했을때 user의 id를 반환한다고 이해를 했었거든요!
오버라이드를 하여 반환형을 바꾸지 못하는 이유로 Name으로 반환하고자 한건지 궁금합니다!

그리고 만약에, name으로 처리해버리게 되면 동명이인 처리에 대한 오류가 있을 것 같습니다!
>> @AuthenticationPrincipal UserDetails userDetails.   userDetails.getUsername()
위 코드를 작성하게 되면 name이 반환될 것이고, 이것을 통해 디비의 정보를 가져오게 되면 동명이인으로 인한 에러가 발생한다고 생각합니다!

2024-07-16 16:26 UTC, DaeYoung0726 commented on src/main/java/gible/domain/security/common/UserDetailsServiceImpl.java
> +    }
이 부분 또한 동명이인으로 인한 에러가 발생할 것이라고 생각합니다!
(SecurityUserDetails 코멘트에 적어놨음.)

2024-07-16 16:39 UTC, daeyoung0726 requested changes
고생하셨습니다!
코멘트 확인 부탁드립니다!

2024-07-16 16:39 UTC, daeyoung0726 commented on src/main/java/gible/domain/security/common/SecurityUserDetails.java
>      }
이 부분에서 user의 이름인 name을 반환하셨는데
카톡으로 얘기했을때 user의 id를 반환한다고 이해를 했었거든요!
오버라이드를 하여 반환형을 바꾸지 못하는 이유로 Name으로 반환하고자 한건지 궁금합니다!

그리고 만약에, name으로 처리해버리게 되면 동명이인 처리에 대한 오류가 있을 것 같습니다!
> @AuthenticationPrincipal UserDetails userDetails.   userDetails.getUsername()

위 코드를 작성하게 되면 name이 반환될 것이고, 이것을 통해 디비의 정보를 가져오게 되면 동명이인으로 인한 에러가 발생한다고 생각합니다!

2024-07-16 16:39 UTC, daeyoung0726 commented on src/main/java/gible/domain/security/common/UserDetailsServiceImpl.java
> +}
이 부분도 위에서 말한 내용과 동일한 이유입니다! 동명이인 떄문에!

2024-07-17 03:18 UTC, Tentennball commented on src/main/java/gible/domain/security/common/SecurityUserDetails.java
>      }
깜빡했네요! 수정했는데 getId는 UUID를 반환하여 오버라이딩 함수의 반환타입을 위반하므로 getEmail을 반환하도록(중복에 대한 문제 x) 수정하였습니다!

2024-07-17 03:21 UTC, DaeYoung0726 commented on src/main/java/gible/domain/security/common/SecurityUserDetails.java
>      }
확인했습니다~ merge하셔도 될 것 같습니다!

2024-07-17 03:21 UTC, DaeYoung0726 approved these changes

2024-07-17 03:21 UTC, merged