Feature/hf 84
Likelion-YeungNam-Univ/12th-Gible-BE pull request #15
Opened 2024-07-17 14:31 UTC by Tentennball

## 개요
소셜로그인 구현을 위한 파일들 작성

## 구현 사항
 - KakaoConfig 작성
 - yml파일 수정(추후에 환경변수 설정 해야함 프로젝트 내 환경변수 설정을 위해 ${}로 설정하지 않고 하드코딩)
 - AuthService, AuthController 일부 구현
 - KakaoApi연결 로직 작성

## 기타
 - 위에서 말했지만 yml파일 핫픽스 필요
 - 로그인 시 Redis 연동 필요

2024-07-17 15:16 UTC, DaeYoung0726 requested changes
복잡할텐데 고생하셨습니다!
확인이 필요한 부분에 대해 코멘트 남겨두겠습니다!

2024-07-17 15:16 UTC, DaeYoung0726 commented on src/main/java/gible/domain/auth/service/AuthService.java
> +            throw new CustomException(ErrorType.NEED_SIGNUP);
> User user = userService.findByEmail(kakaoUserInfo.email());

이 부분에서 userService.findByEmail 메서드를 확인해보니

> return userRepository.findByEmail(email).orElseThrow(()-> new CustomException(ErrorType.USER_NOT_FOUND));

위와 같이 값이 없다면, 예외 처리를 하게 됩니다! 그래서 null의 값을 반환하지 않고 메서드는 예외 처리로 인한 종료가 되어 버립니다!

만약, 디비에 저장되어 있는지 확인하는 목적이라면 처음에 적용했던 .isExist 를 사용하는 것이 괜찮다고 생각합니다

2024-07-17 15:16 UTC, DaeYoung0726 commented on src/main/java/gible/domain/user/service/UserService.java
> -        return userRepository.findByEmail(email).isPresent();
이 코멘트는 위 코멘트에 대해서 하는 것인데,
만약에 .isExist를 사용하게 된다면,
이 메서드는 단순히 디비에 데이터가 저장되어 있는지 확인하는 메서드로 보이는데
> userRepository.findByEmail(email).isPresent();

위와 같은 호출을 하게되면 '사용자 전체'객체를 조회하기 때문에 메모리 사용량이 크다고 판단됩니다!
그래서
> boolean existsByEmail(String email);

jpa 네이밍 메서드로 위와 같은 메서드를 사용한다면 단순히 존재 여부만 판단하기 때문에, 보다 적은 메모리 사용량을 기대할 수 있습니다!

2024-07-17 15:52 UTC, DaeYoung0726 commented
보다가 추가적인 궁금한 것이 있어서 코멘트 하나 추가하겠습니다!
지금은 소셜 로그인만 구현한 상태이고, 회원가입 로직은 아직 구현되지 않은게 맞죠?

2024-07-18 03:03 UTC, Tentennball commented on src/main/java/gible/domain/auth/service/AuthService.java
> +            throw new CustomException(ErrorType.NEED_SIGNUP);
jwt토큰을 생성할때 user가 필요해서 boolean으로 반환을 하지 못하게 처리하였습니다! 대신 userService의 로직을 수정하여 찾지 못했다면 null을 반환하도록 처리했습니다!

2024-07-18 03:05 UTC, Tentennball commented
> 보다가 추가적인 궁금한 것이 있어서 코멘트 하나 추가하겠습니다! 지금은 소셜 로그인만 구현한 상태이고, 회원가입 로직은 아직 구현되지 않은게 맞죠?

네 맞습니다! 로직의 흐름은 findByEmail에 의해 유저를 찾지 못하면 510오류를 발생시키고, 프론트는 501오류를 catch하면 닉네임을 입력하는 uri로 리다이렉트 시키고, 후에 signUp으로 다시 요청을 보내게 됩니다!

2024-07-18 03:06 UTC, DaeYoung0726 approved these changes

2024-07-18 03:16 UTC, merged