HF-85 User, Auth Controller, Service 작성
Likelion-YeungNam-Univ/12th-Gible-BE pull request #17
Opened 2024-07-19 14:01 UTC by Tentennball

## 개요
User, Auth 컨트롤러 서비스 로직 작성
## 구현사항
- MyPage 기능 구현, 참여한 이벤트 조회 구현
- 로그인, 로그이웃, 회원가입 구현

## 기타
- ApiUtil->SuccessRes로 변경
- ErrorDto->ErrorRes로 변경

2024-07-19 16:10 UTC, DaeYoung0726 requested changes
고생하셨습니다!
코멘트에 질문내용 달아놨습니다!

2024-07-19 16:10 UTC, daeyoung0726 commented on src/main/java/gible/domain/user/controller/UserController.java
> +    }
참여한 이벤트에 대해서 불러오는 부분을 ParticipateController에 구현해 두었긴 했습니다!
저도 UserController이 좋을지 ParticipateController이 좋을지 고민을 하다가 마이페이지에서 띄우긴 하지만, 이벤트 참여와 관련되어 있다보니 이 곳에 구현한 것 같습니다!

그리고 참여한 이벤트의 목록만 가져오다 보니  제가 구현한 부분 같은 경우에는 
> public record EventInfoRes(
        UUID eventId,
        String title
) {
}

이렇게 dto를 만들어 반환을 하였습니다.

어디에 둘지는 상의한 후에 변경하는게 좋다고 생각하고 제가 구현한 코드에 대해서 자세히 보시려면 develop 브랜치에서 ParticipateController 컨트롤러 봐주세요! (아직 api를 my-page에서 user로 안바꿈)

2024-07-19 16:10 UTC, daeyoung0726 commented on src/main/java/gible/domain/user/service/UserService.java
> +                .stream().map(EventSummaryRes::fromEntity).toList();
이 부분도 위에서 말한 부분과 동일하고, 이벤트 참여 항목을 조회하다 보니 ParticipateService에 두었습니다!

아마도 개발 과정 중에 제가 pr을 올린 후 머지를 하여서 Participate 구현에 대한 내용이 없었나봅니다!

2024-07-19 16:10 UTC, daeyoung0726 commented on src/main/java/gible/domain/auth/controller/AuthController.java
> +
제가 login 로직과 renewToken 로직을 보고 예상을 했을 때, 클라이언트에서 accessToken, refreshToken을 로컬 or 세션 스토리지 or 개인 변수(메모리)에 저장을 하는 것을 고려하고 재발급할때 refreshToken을 json으로 보내는 것 같습니다!

제가 생각하는 각 방식에 대해서 우려되는 점을 말씀드리겠습니다!
1. 스토리지 : XSS 공격에 매우 취약해서 악성 스크립트가 스토리지에 접근해서 토큰을 탈취할 수 있다.
2. 메모리(변수 사용): SPA방식을 사용하면 이 방식을 이용하여 토큰을 저장하면 XSS 공격으로부터 좋은 효과를 볼 수 있다. 하지만, 새로고침을 하면 토큰이 사라지게 재발급을 한다.

공격 우려가 있더라도 스토리지에 저장하는 방식을 사용한다면 현재 작성하신 코드를 그대로 사용해도 될 것 같습니다.
하지만 2번. SPA의 이점을 살려 변수에 access, refreshToken을 모두 담는다면 새로고침할떄마다 두 토큰 모두 다 사라지기 때문에 재발급의 의미가 사라질 것 같습니다

제가 생각하는 방법이 100프로 정답일 순 없지만, 아래와 같은 방식 또한 있어서 남겨드리겠습니다.
1. accessToken은 메모리(로컬 변수)에 저장 - XSS 공격으로부터 안전
2. refreshToken은 Cookie에 저장. - httpOnly 속성 사용하면 XSS 공격으로부터 안전

아래는 제가 작성한 블로그의 일부분을 들고와봤습니다! (여러가지를 찾아보고 내린 생각이라 정확하지 않을 수 있습니다!)
> Access Token같은 경우에는 인증에 있어 직접적인 영향을 끼친다. 또한, 탈취의 위험을 낮추기 위해 만료 시간을 짧게 한다. 그래서 새로고침하면 사라지기는 하지만, 메모리의 로컬변수에 저장하고 사용하면 보안성을 높일 수 있고, 만료시간 또한 짧기에 적절하다고 생각한다.

>Refresh Token같은 경우에는 인증에 있어 직접적인 영향을 끼치진 않지만, Access Token 재발급에 있어 중요한 역할을 한다. 그래서, XSS를 방지할 수 있는 HttpOnly 속성을 적용한 쿠키에 저장을 하는 것이 적절하다고 생각한다. 추가적으로, CSRF 공격을 통해 공격을 우회하려면 요청 보내는 클라이언트의 주소를 사용하게 되는데, 응답 또한, 그 주소로 보내게 된다. 즉, Refresh Token으로 요청을 보내도 Access Token은 응답으로 오기 때문에 CSRF의 위험으로도 벗어날 수 있다.

[https://velog.io/@pdy000726/JWTAccessToken-RefreshToken#3-%EB%A1%9C%EC%BB%AC-%EC%8A%A4%ED%86%A0%EB%A6%AC%EC%A7%80-localstorage]()

쓰다보니 코멘트가 길어졌는데 만약 저의 방식을 적용한다면 변경될 로직은 아래와 같습니다.
1. login 메서드에서 refreshToken은 cookie로 보냄(프론트에서도 처리가 가능함. 하지만, 찾아보기로는 속성처리는 서버에서 처리하는게 더 간편하다고함.)
2. renewToken 메서드에서 cookie에 들어있는 refreshToken을 가져오기 (HttpServletRequest request 이용)


어디까지나 저의 생각이고 얘기를 더 나눠보면 좋을 것 같습니다!

2024-07-19 16:10 UTC, DaeYoung0726 commented on src/main/java/gible/domain/auth/service/AuthService.java
> +    }
제가 이 로직을 보고 JwtTokenProvider.java를 다시 보고 난 후에 생각이 났습니다.

저는 refreshToken에 accessToken과 같은 정보를 넣는 이유 중 하나가 accessToken을 재발급할때 refreshToken에 들어있는 정보를 통해 바로 accessToken을 재발급해줄 수 있기 때문이라고 생각합니다. (위와 같이 `User user = userService.findById(uuid);`를 사용하면 db에 쿼리를 날림)

그래서 redis에 refreshToken을 저장 -> 클라이언트에서 재발급을 위해 refreshToken을 보냄 -> refreshToken이 redis에 존재하는지 확인 -> 존재한다면 TTL이 지나지 않은것이기에 refreshToken의 payload에서 정보 파싱 (userId, role 등) -> 그 정보를 통해 accessToken 재발급

이런 형식으로 한다면 db에 추가적인 쿼리를 안날릴 것이고 refreshToken에 accessToken과 같은 정보를 저장한다는 장점을 살릴 수 있을 것 같습니다!

만약 이러한 방식으로 한다면
`public String generateRefreshToken(User user)
public String generateAccessToken(User user)`
이 부분을
`public String generateRefreshToken(String userId, String role)
public String generateAccessToken(String userId, String role)`
으로 바뀔 것 같습니다!

2024-07-19 16:10 UTC, DaeYoung0726 commented on src/main/java/gible/domain/auth/service/AuthService.java
> +    }
이 부분은 로그아웃한다면 user의 정보를 삭제시킨다는 건가요?

2024-07-19 16:10 UTC, DaeYoung0726 commented on src/main/java/gible/domain/user/service/UserService.java
> +    public void signUp(@Valid SignUpReq signUpReq) {
이 부분에서 유효성 검사를 위한 Valid를 service에 추가하셨는데
controller에 `@Valid @RequestBody SignUpReq signUpReq` 이렇게 추가하시면 service에 가기 전제 오류 문구가 나타날 것이라고 생각합니다!

2024-07-19 16:10 UTC, DaeYoung0726 commented on src/main/java/gible/domain/user/dto/SignUpReq.java
> +        @NotBlank(message = "전화번호 입력은 필수입니다.")
휴대전화에 대한 검증 패턴도 있으면 좋을 것 같습니다!
ex) 010-12345-1234 <- 중간에 5자리 : 오류
010-1234-56789 <- 마지막이 5자리 : 오류
등

2024-07-19 18:25 UTC, Tentennball reviewed
수정하고 상의할 내용에 대해서는 커멘트 달았습니다! 리프레시토큰재발급 로직도 추후에 구현하겠습니다!

2024-07-19 18:25 UTC, Tentennball commented on src/main/java/gible/domain/auth/controller/AuthController.java
> +
쿠키를 사용하여 쿠키에 리프레시토큰 저장하는것 동의합니다! 해당 의견 반영하여 로직 수정했습니다!

2024-07-19 18:25 UTC, Tentennball commented on src/main/java/gible/domain/auth/service/AuthService.java
> +    }
제가 이때 정줄을 놨는지 저기에 withdraw 로직을 작성해놨네요,,, withdraw 메서드 만들어서 다시 커밋했습니다!

2024-07-19 18:25 UTC, Tentennball commented on src/main/java/gible/domain/user/controller/UserController.java
> +    }
앗 제가 pr 봤던걸 제대로 반영 못했네요.... 라우팅이 user로 되어있어서 저도 생각했긴 한데... 이거때문에 충돌이 발생했겠군요 ㅜㅜ 제생각에 EventInfoRes는 디자인에 따라서 해당 dto를 사용할지 말지 고민해봐야할것 같습니다! 이는 프론트랑 상의 후 결정하고, 일단 제가 짠 로직은 주석처리해둘게요!

2024-07-19 18:25 UTC, Tentennball commented on src/main/java/gible/domain/user/dto/SignUpReq.java
> +        @NotBlank(message = "전화번호 입력은 필수입니다.")
-를 넣어서 할까요 그냥 할까요?? 결정에 따라서 정규표현식 사용해서 검증로직 구현하겠습니다!

2024-07-19 18:25 UTC, Tentennball commented on src/main/java/gible/domain/user/dto/SignUpReq.java
> +        @NotBlank(message = "전화번호 입력은 필수입니다.")
일단 -넣어서 구현했습니다!

2024-07-19 18:49 UTC, jinlee1703 commented on src/main/java/gible/domain/auth/util/CookieUtil.java
> +        cookie.setMaxAge(7 * 24 * 60 * 60);
refreshToken의 수명이 노출되었을 때 어떤 일이 일어날 수 있을까요?

2024-07-20 02:28 UTC, DaeYoung0726 commented on src/main/java/gible/domain/user/controller/UserController.java
> +    }
넵 나중에 어디에 두고 요청을 받을지 논의해보죠!

2024-07-20 02:29 UTC, DaeYoung0726 commented on src/main/java/gible/domain/user/dto/SignUpReq.java
> +        @NotBlank(message = "전화번호 입력은 필수입니다.")
이부분은 일요일에 프론트 분들과 함께 얘기해보면 좋을 것 같습니다!!

2024-07-20 15:22 UTC, DaeYoung0726 requested changes
cookie관련해서 몇가지 코멘트 달았습니다!!

2024-07-20 15:22 UTC, DaeYoung0726 commented on src/main/java/gible/domain/auth/util/CookieUtil.java
> +    }
쿠키를 설정할 때, SameSite 설정이 있습니다. SameSite 설정은 제 3자에서 요청 (다른 도메인에서의 요청)에 대해서 허용을 할지 안할지를 설정하는 것입니다.

설정의 종류로는 3가지가 있는데
- SameSite=Strict : 쿠키가 오직 동일한 사이트에서만 전송. 도메인과 서브도메인이 완전히 일치하여야함.
 ex) 도메인: example.com, 서브도메인: www.example.com
- SameSite=Lax: 쿠키가 동일한 사이트에서만 전송되지만, 일부 경우에는 제3자에도 전송
- SameSite=None: 쿠키가 동일한 사이트와 제3자에게 모두 전송.

보통 프론트 서버와 백엔드 서버는 도메인이 다르기 때문에 SameSite=None 설정을 해줘야 쿠키가 제대로 전달이 됩니다!
이렇게하면 보안적인 문제가 발생할 수 있지 않을까? 라는 생각을 할 수 있는데 secure속성을 true로 해주어 https에서만 접근할 수 있도록 설정해주면 보안적인 문제를 해결할 수 있습니다.

제가 적용할 떄 ` Cookie cookie = new Cookie("refreshToken", refreshToken);`와 같이 Cookie로 반환하면 SameSite 설정이 안되더라고요!
그래서, 

        public ResponseCookie createCookie(String key, String value) {
                return ResponseCookie.from(key, value)
                        .path("/")
                        .httpOnly(true)
                        .maxAge(COOKIE_REFRESH_EXPIRATION)
                        .secure(true)
                        .sameSite("None")
                        .build();
            }
위와 같이 ResponseCookie를 사용하시면 sameSite 설정이 됩니다!

2024-07-20 15:22 UTC, DaeYoung0726 commented on src/main/java/gible/domain/auth/controller/AuthController.java
> +        return ResponseEntity.ok().body(authService.reIssueToken(renewTokenReq));
쿠키로 설정하시면 받아올 때도 http에 담겨져 있기 때문에
`public ResponseEntity<?> renewToken(@CookieValue("refreshToken") String refreshToken)`
이렇게 받아오시면 바로 refreshToken을 받아올 수 있어요!

p.s. 저는 직접 찾는 구문을 작성하였으나 다른 방법이 있나 찾아보다가 위와 같은 CookieValue어노테이션이 있는지 처음 알았네요!

2024-07-21 11:43 UTC, Tentennball commented on src/main/java/gible/domain/auth/util/CookieUtil.java
> +        cookie.setMaxAge(7 * 24 * 60 * 60);
리프레시 토큰의 수명이 노출되면 공격자가 토큰의 수명을 수정해서 토큰 시스템을 붕괴시킬 수 있을 것 같다는 생각이 드네요!! 코드 수정해야겠습니다..! 감사합니다!

2024-07-21 12:57 UTC, DaeYoung0726 approved these changes
고생많으셨습니다!
코드가 깔끔하고 배워가는게 많은 코드였습니다!

2024-07-21 12:57 UTC, DaeYoung0726 commented on src/main/java/gible/domain/auth/service/AuthService.java
> +        );
이러한 코드로 재발급 하는 로직이 저한테는 새롭네요!
배워가겠습니다!!

2024-07-21 12:57 UTC, DaeYoung0726 commented on src/main/java/gible/domain/security/jwt/JwtTokenProvider.java
>  public class JwtTokenProvider {
JwtTokenProvider 클래스 자체가 저는 좀 지저분한 느낌이었는데
이 코드를 보고 많이 배워갑니다! 깔끔한 코드 잘 배워갑니다!

2024-07-21 12:58 UTC, merged