HF-108 : jwt 인터페이스화
Likelion-YeungNam-Univ/12th-Gible-BE pull request #23
Opened 2024-07-28 15:44 UTC by Tentennball

## 개요
- Jwt 다형성 구현

## 구현 내용
- JwtTokenProvider 인터페이스화
- AccessTokenProvider, RefreshTokenProvider로 구현체 구현
- 관련된 서비스로직 수정

2024-07-29 07:03 UTC, DaeYoung0726 requested changes
고생하셨습니다!
코멘트 하나만 확인해주시면 감사하겠습니다!

2024-07-29 07:03 UTC, daeyoung0726 commented on src/main/java/gible/domain/security/jwt/JwtAuthenticationFilter.java
> +    }
여기서 저희가 글로벌적으로 처리한 ExceptionHandler을 이용하여 예외처리를 하면 작동이 안돼요!
그 이유는 '클라이언트 -> 필터 -> 디스패쳐 서블릿 -> 인터셉터 -> 컨트롤러' 순으로 동작하고 다시 클라이언트로 갈때도 역순으로 작동을 해요!
하지만, 위 코드는 jwt를 확인하는  것이고 '필터'에 등록되어 있기 때문에, ExceptionHandler가 작동하는 Controller까지 가지 않아요! (에러가 발생하면 '클라이언트 -> 필터 -> 클라이언트' 로 동작)

그래서, 저는 이 부분에 대해서만 따로 예외처리 메서드를 만들었던 기억이 있습니다. (해당 class에)

아래가 동작하는 순서이고, 이 이미지를 참고하면 좋을 것 같습니다!

![image](https://github.com/user-attachments/assets/59f04651-a4c2-42ae-8ac4-60dff5840a39)

2024-07-29 07:05 UTC, Tentennball commented on src/main/java/gible/domain/security/jwt/JwtAuthenticationFilter.java
> +    }
아 따로 ExceptionHandler를 만들어야했던 기억이 나네요!!! 빠뜨리고있던점 짚어주셔서 감사합니다 :D 참고하여 구현하겟습니다! 좋은자료감사해요!!

2024-07-31 11:01 UTC, DaeYoung0726 commented
고생하셨습니다! 머지하셔도 될 것 같습니다!

2024-07-31 11:01 UTC, DaeYoung0726 approved these changes

2024-08-01 02:20 UTC, merged